#!/bin/bash
set -e

# google-chrome --version

echo '--- bundling'
bundle

echo '--- preparing database'
./bin/rake db:create
./bin/rake db:schema:load

# echo '--- setting up sphinx'
# ./bin/rake ts:configure
# ./bin/rake ts:start

echo '--- running specs'
./bin/rspec
